versions:
  "1.91.4":
    folder: all
  "1.91.4-docking":
    folder: all
  "1.91.3":
    folder: all
  "1.91.3-docking":
    folder: all
  "1.91.2":
    folder: all
  "1.91.2-docking":
    folder: all
  "1.91.0":
    folder: all
  "1.91.0-docking":
    folder: all
  "1.90.9":
    folder: all
  "1.90.9-docking":
    folder: all
  # keep 1.90.5 for imguizmo, implot
  "1.90.5":
    folder: all
  "1.90.5-docking":
    folder: all
  # keep 1.88 for implot
  "1.88":
    folder: all
  # keep 1.87 for magnum-integration, diligent-tools
  "1.87":
    folder: all
  # keep 1.86 for implot
  "1.86":
    folder: all
  # keep 1.85 for diligent-tools
  "1.85":
    folder: all
